language: python
python:
  - 3.5
  - 3.6
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

install:
  - pip install .
  - pip install -r test-requirements.txt

script:
  - coverage run -m pytest
  - coverage report -m
  - codecov
  - flake8 .
